#! /usr/bin/env python

import getopt
import sys

from pet_race_job.data_importer import DataImporter


def main(arg):
    options, remainder = getopt.getopt(arg[1:], 'd:h:ks:c', ['directory=', 'help', 'keyspace', 'seeds=', 'create'])

    # if options.d is None: # where foo is obviously your required option
    #    parser.print_help()
    #    sys.exit(1)

    seeds = None
    data_dir = None
    drop_keyspace = None
    create = False

    for opt, arg in options:
        if opt in ('-d', '--directory'):
            data_dir = arg
        if opt in ('-k', '--keyspace'):
            drop_keyspace = True
        if opt in ('-s', '--seeds'):
            seeds = arg
        if opt in ('-c', '--create'):
            create = True
        if opt in ('-h', '--help'):
            print("usage: --directory=data_directory")
            exit(0)

    if data_dir is None:
        exit("no parameter found")

    if drop_keyspace is None:
        drop_keyspace = False

    if seeds is None:
        loader = DataImporter(seeds=['cassandra-0.cassandra.default.svc.cluster.local',
                                     'cassandra-1.cassandra.default.svc.cluster.local'], keyspace='gpmr')
    else:
        loader = DataImporter(seeds=[seeds], keyspace='gpmr')

    if drop_keyspace:
        loader.create_keyspace()

    loader.create_tables()

    if create:
        loader.save_counters()
        # todo move path to config files
        pet_cats = loader.parse_pet_categories(data_dir + '/pet_categories.csv')
        loader.save_pet_categories(pet_cats)

        pets_data = loader.parse_pet_files(data_dir + '/pets/*.csv')

        for p in pets_data:
            loader.save_pets(p['pet'], p['cat'])


if __name__ == '__main__':
    main(sys.argv)
